### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by retorquere** [MartyO256/find-files-by-patterns#1]
when I have a script with only

```
const { downwardDirectoriesSync } = require("find-files-by-patterns");
```

I get 

```
async function* filter(iterable, filter) {
              ^

SyntaxError: Unexpected token *
```

**Comment by MartyO256** [comment]
The `async function*` is used to create an asynchronous generator function, which was introduced in ES2018 along with asynchronous iteration. The error occurs as the `filter` function is declared when the module is imported.
Make sure you are using Node v10.15.2 or above.
